kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: rails-deployment
spec:
  scaleTargetRef:
    kind: Deployment
    name: rails-deployment
    apiVersion: extensions/v1beta1
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
